# Data Preprocessing 

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv(r"C:\Users\patri\OneDrive\Documents\SuperDatascience\Spinescope\SDS-CP033-spinescope\submissions\team-members\patrick-githendu\column_3C_weka.csv")
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(X)


[[ 63.0278175   22.55258597  39.60911701  40.47523153  98.67291675
   -0.25439999]
 [ 39.05695098  10.06099147  25.01537822  28.99595951 114.4054254
    4.56425864]
 [ 68.83202098  22.21848205  50.09219357  46.61353893 105.9851355
   -3.53031731]
 ...
 [ 61.44659663  22.6949683   46.17034732  38.75162833 125.6707246
   -2.70787952]
 [ 45.25279209   8.69315736  41.5831264   36.55963472 118.5458418
    0.21475017]
 [ 33.84164075   5.07399141  36.64123294  28.76764934 123.9452436
   -0.19924909]]


In [4]:
print(y)

['Hernia' 'Hernia' 'Hernia' 'Hernia' 'Hernia' 'Hernia' 'Hernia' 'Hernia'
 'Hernia' 'Hernia' 'Hernia' 'Hernia' 'Hernia' 'Hernia' 'Hernia' 'Hernia'
 'Hernia' 'Hernia' 'Hernia' 'Hernia' 'Hernia' 'Hernia' 'Hernia' 'Hernia'
 'Hernia' 'Hernia' 'Hernia' 'Hernia' 'Hernia' 'Hernia' 'Hernia' 'Hernia'
 'Hernia' 'Hernia' 'Hernia' 'Hernia' 'Hernia' 'Hernia' 'Hernia' 'Hernia'
 'Hernia' 'Hernia' 'Hernia' 'Hernia' 'Hernia' 'Hernia' 'Hernia' 'Hernia'
 'Hernia' 'Hernia' 'Hernia' 'Hernia' 'Hernia' 'Hernia' 'Hernia' 'Hernia'
 'Hernia' 'Hernia' 'Hernia' 'Hernia' 'Spondylolisthesis'
 'Spondylolisthesis' 'Spondylolisthesis' 'Spondylolisthesis'
 'Spondylolisthesis' 'Spondylolisthesis' 'Spondylolisthesis'
 'Spondylolisthesis' 'Spondylolisthesis' 'Spondylolisthesis'
 'Spondylolisthesis' 'Spondylolisthesis' 'Spondylolisthesis'
 'Spondylolisthesis' 'Spondylolisthesis' 'Spondylolisthesis'
 'Spondylolisthesis' 'Spondylolisthesis' 'Spondylolisthesis'
 'Spondylolisthesis' 'Spondylolisthesis' 'Spondylolisthesis'
 'Spo

## Taking care of missing data

In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 0:6])  # Fit on all columns that need imputation
X[:, 0:6] = imputer.transform(X[:, 0:6])

In [6]:
print(X)

[[ 63.0278175   22.55258597  39.60911701  40.47523153  98.67291675
   -0.25439999]
 [ 39.05695098  10.06099147  25.01537822  28.99595951 114.4054254
    4.56425864]
 [ 68.83202098  22.21848205  50.09219357  46.61353893 105.9851355
   -3.53031731]
 ...
 [ 61.44659663  22.6949683   46.17034732  38.75162833 125.6707246
   -2.70787952]
 [ 45.25279209   8.69315736  41.5831264   36.55963472 118.5458418
    0.21475017]
 [ 33.84164075   5.07399141  36.64123294  28.76764934 123.9452436
   -0.19924909]]


### Encoding the Dependent Variable

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [8]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


## Splitting the dataset into the Training set and Test set

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [10]:
print(X_train)

[[ 61.44659663  22.6949683   46.17034732  38.75162833 125.6707246
   -2.70787952]
 [ 63.0278175   22.55258597  39.60911701  40.47523153  98.67291675
   -0.25439999]
 [ 69.62628302  21.12275138  52.76659472  48.50353164 116.8030913
   54.81686729]
 ...
 [ 84.97413208  33.02117462  60.85987263  51.95295747 125.6595336
   74.33340864]
 [ 63.92947003  19.97109671  40.17704963  43.95837332 113.0659387
  -11.05817866]
 [ 35.70345781  19.44325311  20.7         16.26020471 137.5406125
   -0.26348965]]


In [11]:
print(X_test)

[[ 67.41253785  17.44279712  60.14464036  49.96974073 111.12397
   33.15764573]
 [ 63.02630005  27.33624023  51.60501665  35.69005983 114.5066078
    7.4398698 ]
 [ 91.46874146  24.50817744  84.62027202  66.96056402 117.3078968
   52.62304673]
 [ 72.56070163  17.38519079  51.99999999  55.17551084 119.1937238
   32.10853735]
 [ 54.74177518  12.09507205  40.99999999  42.64670314 117.6432188
   40.3823266 ]
 [ 70.39930842  13.46998624  61.19999999  56.92932218 102.3375244
   25.53842852]
 [ 33.84164075   5.07399141  36.64123294  28.76764934 123.9452436
   -0.19924909]
 [ 72.05403412  24.70073725  79.87401586  47.35329687 107.1723576
   56.42615873]
 [ 84.99895554  29.61009772  83.35219438  55.38885782 126.9129899
   71.32117542]
 [ 69.3988184   18.89840693  75.96636144  50.50041147 103.5825398
   -0.44366081]
 [ 65.61180231  23.13791922  62.58217893  42.47388309 124.1280012
   -4.08329841]
 [ 45.25279209   8.69315736  41.5831264   36.55963472 118.5458418
    0.21475017]
 [ 43.20318499  19

In [12]:
print(y_train)

[1 0 2 2 2 2 2 2 2 2 2 1 1 0 2 2 2 1 0 2 2 1 0 2 2 2 0 1 0 1 2 2 1 2 0 2 1
 1 2 1 1 1 0 0 2 1 2 0 1 2 2 2 2 1 0 2 1 2 2 2 2 2 1 0 1 1 0 0 0 0 1 0 1 2
 0 0 1 2 1 1 2 2 2 1 1 1 0 1 1 0 0 2 2 0 2 0 1 2 1 2 2 2 1 2 1 0 2 2 2 2 1
 2 1 1 2 2 1 2 2 1 1 0 2 1 1 1 2 1 2 1 2 2 1 2 2 2 2 2 2 1 2 2 2 1 2 2 2 0
 0 0 2 1 0 1 0 1 2 0 1 0 1 1 2 2 1 1 1 2 1 1 0 2 1 0 0 2 2 1 2 2 2 2 2 1 2
 0 2 2 2 1 2 1 2 1 2 2 2 2 2 2 2 1 2 2 1 0 2 2 0 2 0 2 0 0 0 1 0 2 2 1 1 1
 2 0 0 0 2 2 1 1 2 0 2 1 1 1 2 1 1 2 2 2 2 2 1 2 1 0]


In [13]:
print(y_test)

[2 1 2 2 2 2 1 2 2 1 1 1 0 0 1 2 1 1 1 2 2 1 0 2 0 2 2 2 2 2 2 1 1 0 0 2 0
 1 2 2 1 1 2 1 2 2 1 1 2 1 2 1 0 2 2 0 2 2 0 2 0 2]


## Feature Scaling

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [15]:
print(X_train)

[[ 0.06676731  0.55096591 -0.31581494 -0.31561219  0.59294449 -0.74839697]
 [ 0.15935097  0.53651871 -0.6692242  -0.18879786 -1.58014878 -0.68669034]
 [ 0.5457044   0.39143676  0.03948044  0.40188538 -0.12082436  0.69838839]
 ...
 [ 1.44435183  1.59874181  0.47541077  0.65567734  0.59204371  1.18924228]
 [ 0.21214454  0.27458106 -0.63863349  0.06747476 -0.42163327 -0.95841251]
 [-1.44054525  0.22102201 -1.68773087 -1.97042165  1.54836922 -0.68691895]]


In [16]:
print(X_test)

[[ 4.16085166e-01  1.80404425e-02  4.36886027e-01  5.09761905e-01
  -5.77945185e-01  1.53644666e-01]
 [ 1.59262119e-01  1.02190487e+00 -2.30859405e-02 -5.40867498e-01
  -3.05671694e-01 -4.93174375e-01]
 [ 1.82462428e+00  7.34947986e-01  1.75522333e+00  1.75986397e+00
  -8.01918217e-02  6.43212351e-01]
 [ 7.17520510e-01  1.21952635e-02 -1.81085042e-03  8.92777126e-01
   7.16011673e-02  1.27258898e-01]
 [-3.25813476e-01 -5.24580657e-01 -5.94306704e-01 -2.90315504e-02
  -5.32012607e-02  3.35350159e-01]
 [ 5.90966590e-01 -3.85071345e-01  4.93731137e-01  1.02181403e+00
  -1.28517912e+00 -3.79836765e-02]
 [-1.54955839e+00 -1.23699322e+00 -8.29084105e-01 -1.05018476e+00
   4.54057985e-01 -6.85303258e-01]
 [ 6.87854109e-01  7.54486577e-01  1.49957450e+00  3.17256703e-01
  -8.96016280e-01  7.38863128e-01]
 [ 1.44580530e+00  1.25262785e+00  1.68692053e+00  9.08474158e-01
   6.92936249e-01  1.11348263e+00]
 [ 5.32385887e-01  1.65737750e-01  1.28909549e+00  5.48806074e-01
  -1.18496599e+00 -6.9145