# Random Forest Classification

## Importing the libraries

In [70]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [71]:
dataset = pd.read_csv('column_3C_weka.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Splitting the dataset into the Training set and Test set

In [72]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [73]:
print(X_train)

[[ 46.23639915  10.0627701   37.          36.17362905 128.0636203
   -5.10005333]
 [ 49.78212054   6.46680486  52.99999999  43.31531568 110.8647831
   25.33564729]
 [ 38.04655072   8.30166942  26.23683004  29.7448813  123.8034132
    3.88577349]
 ...
 [ 86.04127982  38.75066978  47.87140494  47.29061004 122.0929536
   61.98827709]
 [ 41.35250407  16.57736351  30.70619135  24.77514057 113.2666746
   -4.49795756]
 [ 56.66829282  13.45820343  43.76970978  43.21008939  93.69220863
   21.10812135]]


In [74]:
print(y_train)

['Normal' 'Spondylolisthesis' 'Normal' 'Hernia' 'Spondylolisthesis'
 'Hernia' 'Hernia' 'Normal' 'Normal' 'Normal' 'Spondylolisthesis' 'Hernia'
 'Spondylolisthesis' 'Normal' 'Hernia' 'Spondylolisthesis' 'Normal'
 'Normal' 'Spondylolisthesis' 'Normal' 'Spondylolisthesis' 'Normal'
 'Normal' 'Normal' 'Normal' 'Hernia' 'Spondylolisthesis'
 'Spondylolisthesis' 'Spondylolisthesis' 'Spondylolisthesis'
 'Spondylolisthesis' 'Normal' 'Spondylolisthesis' 'Normal' 'Hernia'
 'Normal' 'Hernia' 'Normal' 'Spondylolisthesis' 'Spondylolisthesis'
 'Normal' 'Spondylolisthesis' 'Hernia' 'Spondylolisthesis' 'Hernia'
 'Spondylolisthesis' 'Spondylolisthesis' 'Normal' 'Hernia'
 'Spondylolisthesis' 'Spondylolisthesis' 'Normal' 'Normal'
 'Spondylolisthesis' 'Spondylolisthesis' 'Spondylolisthesis' 'Normal'
 'Spondylolisthesis' 'Normal' 'Normal' 'Spondylolisthesis' 'Hernia'
 'Spondylolisthesis' 'Spondylolisthesis' 'Normal' 'Normal'
 'Spondylolisthesis' 'Hernia' 'Spondylolisthesis' 'Spondylolisthesis'
 'Spondylolist

In [75]:
print(X_test)

[[ 50.67667667   6.46150127  35.          44.2151754  116.5879699
   -0.21471061]
 [ 85.64378664  42.68919513  78.7506635   42.95459151 105.1440758
   42.88742577]
 [ 54.60031622  21.48897426  29.36021618  33.11134196 118.3433212
   -1.47106726]
 [ 56.10377352  13.10630665  62.63701952  42.99746687 116.2285032
   31.17276727]
 [ 50.20966979  29.76012218  36.10400731  20.44954761 128.2925148
    5.74061408]
 [ 48.80190855  18.01776202  51.99999999  30.78414653 139.1504066
   10.44286169]
 [ 63.07361096  24.41380271  53.99999999  38.65980825 106.4243295
   15.77969683]
 [ 78.40125389  14.04225971  79.69426258  64.35899418 104.7312342
   12.39285327]
 [ 86.472905    40.30376567  61.14101155  46.16913933  97.4041888
   55.75222146]
 [ 47.80555887  10.68869819  53.99999999  37.11686068 125.3911378
   -0.40252322]
 [ 81.11260488  20.69044356  60.68700588  60.42216132  94.01878339
   40.51098228]
 [ 76.1472121   21.93618556  82.96150249  54.21102654 123.9320096
   10.43197194]
 [ 64.26150724 

In [76]:
print(y_test)

['Normal' 'Spondylolisthesis' 'Normal' 'Normal' 'Hernia' 'Normal' 'Hernia'
 'Spondylolisthesis' 'Spondylolisthesis' 'Normal' 'Spondylolisthesis'
 'Spondylolisthesis' 'Normal' 'Spondylolisthesis' 'Spondylolisthesis'
 'Spondylolisthesis' 'Normal' 'Spondylolisthesis' 'Normal' 'Normal'
 'Hernia' 'Normal' 'Hernia' 'Spondylolisthesis' 'Spondylolisthesis'
 'Hernia' 'Hernia' 'Normal' 'Normal' 'Spondylolisthesis'
 'Spondylolisthesis' 'Spondylolisthesis' 'Normal' 'Spondylolisthesis'
 'Spondylolisthesis' 'Spondylolisthesis' 'Spondylolisthesis'
 'Spondylolisthesis' 'Spondylolisthesis' 'Normal' 'Spondylolisthesis'
 'Spondylolisthesis' 'Normal' 'Spondylolisthesis' 'Normal' 'Hernia'
 'Spondylolisthesis' 'Hernia' 'Spondylolisthesis' 'Hernia' 'Normal'
 'Spondylolisthesis' 'Normal' 'Spondylolisthesis' 'Spondylolisthesis'
 'Hernia' 'Spondylolisthesis' 'Spondylolisthesis' 'Hernia' 'Hernia'
 'Normal' 'Hernia' 'Hernia' 'Spondylolisthesis' 'Normal' 'Hernia'
 'Spondylolisthesis' 'Spondylolisthesis' 'Spondylol

## Feature Scaling

In [77]:
# Apply log1p transformation to degree_spondylolisthesis (last column, index 5)
X_train[:, 5] = np.log1p(X_train[:, 5])
X_test[:, 5] = np.log1p(X_test[:, 5])

C:\Users\patri\AppData\Local\Temp\ipykernel_29204\3862945560.py:2: RuntimeWarning: invalid value encountered in log1p
  X_train[:, 5] = np.log1p(X_train[:, 5])
C:\Users\patri\AppData\Local\Temp\ipykernel_29204\3862945560.py:3: RuntimeWarning: invalid value encountered in log1p
  X_test[:, 5] = np.log1p(X_test[:, 5])


In [78]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [79]:
print(X_train)

[[-8.23620505e-01 -7.48552177e-01 -7.80676174e-01 -5.15038121e-01
   7.62800696e-01             nan]
 [-6.19568881e-01 -1.11735345e+00  7.57498781e-02  9.44917986e-03
  -4.80235258e-01  3.93080866e-01]
 [-1.29493556e+00 -9.29170210e-01 -1.35679237e+00 -9.87167007e-01
   4.54896706e-01 -6.81128581e-01]
 ...
 [ 1.46709827e+00  2.19367144e+00 -1.98766523e-01  3.01395819e-01
   3.31274233e-01  9.49141672e-01]
 [-1.10468227e+00 -8.04171516e-02 -1.11756253e+00 -1.35214604e+00
  -3.06639947e-01             nan]
 [-2.23278681e-01 -4.00317407e-01 -4.18316435e-01  1.72133410e-03
  -1.72137309e+00  2.81503087e-01]]


In [80]:
print(X_test)

[[-5.68088347e-01 -1.11789738e+00 -8.87729430e-01  7.55351088e-02
  -6.65952615e-02 -1.84680151e+00]
 [ 1.44422306e+00  2.59760559e+00  1.45409607e+00 -1.70424958e-02
  -8.93696051e-01  7.18739701e-01]
 [-3.42288027e-01  4.23316384e-01 -1.18960804e+00 -7.39933271e-01
   6.02717326e-02             nan]
 [-2.55766028e-01 -4.36407851e-01  5.91587040e-01 -1.38937184e-02
  -9.25755081e-02  5.20739636e-01]
 [-5.94963981e-01  1.27160319e+00 -8.28635641e-01 -1.66981870e+00
   7.79343913e-01 -4.75912735e-01]
 [-6.75978798e-01  6.73097492e-02  2.22232499e-02 -9.10843101e-01
   1.56409173e+00 -1.38450287e-01]
 [ 1.45338992e-01  7.23286038e-01  1.29276506e-01 -3.32452482e-01
  -8.01166459e-01  1.05650503e-01]
 [ 1.02742478e+00 -3.40416746e-01  1.50460375e+00  1.55490233e+00
  -9.23533937e-01 -3.81102769e-02]
 [ 1.49193773e+00  2.35295655e+00  5.11510778e-01  2.19034722e-01
  -1.45309188e+00  8.82662550e-01]
 [-7.33317417e-01 -6.84357153e-01  1.29276506e-01 -4.45766947e-01
   5.69648578e-01 -2.0210

## Training the Random Forest Classification model on the Training set

In [81]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

## Predicting the Test set results

In [82]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['Normal' 'Normal']
 ['Spondylolisthesis' 'Spondylolisthesis']
 ['Hernia' 'Normal']
 ['Spondylolisthesis' 'Normal']
 ['Normal' 'Hernia']
 ['Normal' 'Normal']
 ['Spondylolisthesis' 'Hernia']
 ['Spondylolisthesis' 'Spondylolisthesis']
 ['Spondylolisthesis' 'Spondylolisthesis']
 ['Normal' 'Normal']
 ['Spondylolisthesis' 'Spondylolisthesis']
 ['Normal' 'Spondylolisthesis']
 ['Normal' 'Normal']
 ['Spondylolisthesis' 'Spondylolisthesis']
 ['Spondylolisthesis' 'Spondylolisthesis']
 ['Spondylolisthesis' 'Spondylolisthesis']
 ['Normal' 'Normal']
 ['Spondylolisthesis' 'Spondylolisthesis']
 ['Normal' 'Normal']
 ['Normal' 'Normal']
 ['Hernia' 'Hernia']
 ['Normal' 'Normal']
 ['Normal' 'Hernia']
 ['Spondylolisthesis' 'Spondylolisthesis']
 ['Spondylolisthesis' 'Spondylolisthesis']
 ['Normal' 'Hernia']
 ['Normal' 'Hernia']
 ['Spondylolisthesis' 'Normal']
 ['Normal' 'Normal']
 ['Spondylolisthesis' 'Spondylolisthesis']
 ['Spondylolisthesis' 'Spondylolisthesis']
 ['Spondylolisthesis' 'Spondylolisthesis'

## Making the Confusion Matrix

In [83]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 4 10  1]
 [ 2 20  2]
 [ 0  1 38]]


0.7948717948717948